新增新疆维吾尔语
OpenTranslate/OpenTranslate pull request #11
Opened 2020-04-11 03:46 UTC by SilvaQ

新增新疆维吾尔语

2020-04-11 03:48 UTC, SilvaQ commented
上一次提交不注意有test，现在按照要求补充了locales，test 也通过测试了。

2020-04-11 06:08 UTC, elliottzheng requested changes
你好，请在 https://github.com/OpenTranslate/OpenTranslate/blob/60f462d7bad6d3be7d03878bdca46031ea4c05c8/packages/service-google/src/index.ts#L106 这个位置，新增一条记录 `["ug", "ug"],`以声明谷歌翻译器支持此语言。

2020-04-12 00:41 UTC, elliottzheng approved these changes

2020-04-12 00:41 UTC, merged

2020-04-16 13:21 UTC, SilvaQ commented
@elliottzheng 这个更新能发布一个小版本么，我在想沙拉词典做些针对性的调整并提交PR 来着，但是这个库不发布支持，我其他链没法推动了。

2020-04-16 13:24 UTC, crimx commented
你好，谢谢你的 PR！我预计会在下周发布一个版本并合并到沙拉查词中。

你还有计划做其它的整合么。

2020-04-16 13:59 UTC, crimx commented
@SilvaQ 修改已经发布了。如果你需要更多时间整合沙拉查词下周可以延缓一下发布。

2020-04-16 14:53 UTC, SilvaQ commented
> @SilvaQ 修改已经发布了。如果你需要更多时间整合沙拉查词下周可以延缓一下发布。
@crimx 
 暂时还没有动手做，只是在计划中。维吾尔语的书写方式是RTL ,我看做些扩展对现在的沙拉结构来看还是有点难以入手。不知道后期得开个分支，还是通过文本编码区分使用不同的布局方式显示内容。
望能够加入你们对于RTL的支持方面做些贡献。
uybabbage@hotmail.com

2020-04-17 08:53 UTC, crimx commented
沙拉查词的话目前主要是机器翻译才需要 RTL 吧，可以看看 [RTL Guidelines](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/RTL_Guidelines)。理论上应该可以直接支持，但我没有接触过所以也不能确定。打算开发的话可以先开个 WIP PR 说不定会有其他感兴趣开发者看到。

2020-04-20 11:32 UTC, SilvaQ commented
> 沙拉查词的话目前主要是机器翻译才需要 RTL 吧，可以看看 [RTL Guidelines](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/RTL_Guidelines)。理论上应该可以直接支持，但我没有接触过所以也不能确定。打算开发的话可以先开个 WIP PR 说不定会有其他感兴趣开发者看到。

@crimx  现在的沙拉什么也不做是没问题的，但是因为书写方向不同，从左往右写和从右往左写的内容混合在一起时会出现混乱的现象导致无法正常阅读，纯rtl时不会有问题的。 还有没有字体时阅读起来相当的不美观。 rtl和lrt方面我们应该算是已经有足够多的经验。
所以沙拉中新增ug后我打算看看效果，然后针对性的做一些调整,调整也没那么复杂，只是元素的css direction为rtl,然后font-face加载字体指定一下就可以。这些调整我能做主进行调整并维护。

2020-04-20 11:35 UTC, crimx commented
好的谢谢你🙏

2020-04-20 11:40 UTC, SilvaQ commented
说起来很复杂，其实就这几行代码的事儿，如果你方便的话，当翻译目标为ug时 显示区域的样式使用rtl专属样式和字体的话问题彻底解决了的。这个对使用rtl的少数民族来说的意义非常大。


```css
@font-face {
  font-family: "UKIJ Tuz Basma";
  src: url("https://ws-image-cdn.subat.cn/fonts/ukij-tuz-basma-bold/UKIJTuzBasma-Bold.eot");
  src: url("https://ws-image-cdn.subat.cn/fonts/ukij-tuz-basma-bold/UKIJTuzBasma-Bold.eot?#iefix")
      format("embedded-opentype"),
    url("https://ws-image-cdn.subat.cn/fonts/ukij-tuz-basma-bold/UKIJTuzBasma-Bold.woff2")
      format("woff2"),
    url("https://ws-image-cdn.subat.cn/fonts/ukij-tuz-basma-bold/UKIJTuzBasma-Bold.woff")
      format("woff"),
    url("https://ws-image-cdn.subat.cn/fonts/ukij-tuz-basma-bold/UKIJTuzBasma-Bold.ttf")
      format("truetype"),
    url("https://ws-image-cdn.subat.cn/fonts/ukij-tuz-basma-bold/UKIJTuzBasma-Bold.svg#UKIJTuzBasma-Bold")
      format("svg");
  font-style: normal;
}

/* 目标内容显示区域调整书写方向是rtl，并指定美化显示用的字体 */
.target_rtl_elem {
  direction: rtl;
  font-family: "UKIJ Tuz Basma" !important;
}
```

2020-04-22 14:49 UTC, crimx commented
谢谢。像机器翻译并排显示两种语言，另外一种语言需要向右对齐吗？如何阅读起来比较方便。

2020-04-23 02:41 UTC, SilvaQ commented
@crimx 
我截图了你看看估计明白了：
![image](https://user-images.githubusercontent.com/46706370/80052079-5ea37200-854c-11ea-9859-28e33876fd0d.png)

一个div中假设有很多个p,那么其中一个或者多个存在少数民族从右往左写的内容也就是direction为RTL 时，不管具体内容是什么直接往父容器 也就是包含内容的p标签设置 css样式direction:rtl 或者属性dir="rtl" 内容马上就能正常显示，如果不设置rtl 内容中存在少数民族内容和非rtl书写内容时就因为两个内容的书写方式不一样各自找自己的方向导致没法正常阅读。所以需要给父容器书整体rlt，这时书写方向统一了，大家都是一个方向，只不过ltr的还是原样链接rtl内容该待的位置上。有点类似css中连续的元素设置不同的float后书序颠倒了。

所以如果沙拉字典呀接入的话 只要翻译出的目标为ug 时 显示结果的容器给它设置一个rtl就完事儿。
如果有无法通过ug来判断的情况，我们一般通过unicode范围来判断是否维吾尔语，然后进行rtl处理:
示例代码如下:
```js
  let viewController = $(docContent).find(".lake-engine-view");
  viewController.children().each((index, domEle) => {
    let elem = $(domEle);
    let text = elem.text();
    let reg = /[\u0626-\u06d5]+/g;
    if (reg.test(text)) {
      elem.attr("dir", "rtl");
      elem.css("direction", "rtl");
      elem.css("text-align", "right");
    }
  });
```
也就是 内容中只要存在 \u0626-\u06d5 这个编码范围的文本 肯定是维吾尔语（ug）内容。

备注：
维吾尔语是书写方向从右往左写的语言，从阿拉伯语中改造、删减、简化而成的属于突厥语系的语言。
我们国内，哈萨克族，柯尔克孜族，维吾尔族，塔塔尔族等少数民族语言和文字都是突厥语系的语言 ug的这个编码范围也包括了上面这几个语言的情况。
如果插件要面向阿拉伯语或者其他书写方式rtl的语言的话 概念是一个概念容器设置rtl 可以看成一个事情去解决，没有特殊例外的情况。

最后我上一个评论贴的样式中使用了font-face 加载字体时因为电脑自带的字体都是国际标准的字母来显示，默认很丑，甚至有些圆角，圆圈不明显，阅读起来有困难，加上专门重新绘制的字体后内容阅读起来无比的舒服。 字体对非rtl内容没有影响，尤其是对中文，英文以及数字。因为维吾尔语的字体只对维吾尔语整个语言组成所使用的32个字母加工，对其他字母不做特殊处理。

2020-04-23 02:48 UTC, SilvaQ commented
@crimx 
我再补充一个图片，望对你的理解有所帮助：
![image](https://user-images.githubusercontent.com/46706370/80053617-ed65be00-854f-11ea-95f2-25a37216fb96.png)

2020-04-23 02:50 UTC, crimx commented
谢谢你的解释。

我不是指混合编排，而是沙拉查词会同时显示原文和译文，你的说法我没有理解错的话另一种语言也应该受 RTL 影响更换方向对齐。这时候沙拉查词的发音喇叭也应该换到右边更方便阅读吧？

2020-04-23 02:53 UTC, SilvaQ commented
rtl 语言的排版确实是你说的那种和中文刚好相反，都是右边到左边。
如果能做到排版也是rtl 是完美的不得了，但如果这方面有困难的话，先把内容和它的容器调整rtl并设置字体，其他所有排版保留不变也不妨使用，对于小喇叭来说它在内容开头最好了。

2020-04-23 04:09 UTC, crimx commented
嗯嗯，因为像一段维吾尔语一段中文交叉这样，中文段落依然左往右阅读，保留左对齐在我（瞎猜）看来更容易找到段落开头，右对齐则更统一样式，所以就比较好奇中文段落是左对齐还是右对齐比较方便。学到了不少知识，谢谢！

2020-04-23 05:55 UTC, crimx commented
@SilvaQ 这么实现正确吗？

![image](https://user-images.githubusercontent.com/6882794/80064202-1a26cf00-856a-11ea-9545-4f14a7ccf345.png)

2020-04-23 06:18 UTC, SilvaQ commented
@crimx 
切换语言区域ltr原样显示看起来会更好

2020-04-23 06:25 UTC, crimx commented
这样

<img width="340" alt="2020-04-23_14-23" src="https://user-images.githubusercontent.com/6882794/80066236-2876ea00-856e-11ea-815d-50a735e4c913.png">

<img width="340" alt="2020-04-23_14-24" src="https://user-images.githubusercontent.com/6882794/80066253-2e6ccb00-856e-11ea-842f-1638b73f5055.png">

2020-04-23 06:26 UTC, crimx commented
也没关系了，这个切换以后可能会移到标题栏中。

2020-04-23 06:27 UTC, SilvaQ commented
@crimx 一直看不惯这个区域来着，刚好趁这个机会我给个建议你看如何
1. 把源语言放上面，目标放在下面
2.这里的布局做重整。选择语言区域完全模仿飞机选择出发地和目的地那种左右中间有方向的效果放在顶部，然后下面区域显示内容。原文和译文结果模仿微信两个人聊天效果，或者类似的效 哈哈，看来给个时间我对这方面做一些贡献好了

2020-04-23 06:29 UTC, SilvaQ commented
> 也没关系了，这个切换以后可能会移到标题栏中。
也行，那你先以这个整一下吧，后面反正可以调整，目前维吾尔语和源语言那个区域显示挺好的

2020-04-23 06:30 UTC, SilvaQ commented
我在外出，手机看不到图片。
我 vx：xierwake

2020-04-23 06:32 UTC, crimx commented
好，就不 hijack 这个 issue 了。